export class EditCarDTO {
  public keyCar = '';
  public powerBHP = 0;
  public powerKW = 0;
  public torqueLBFT = 0;
  public torqueNM = 0;
  public weightLBS = 0;
  public transmission = '';
  public gearBox = 0;
  public weightKG = 0;
  public engineDisplacement = 0;
  public engineConfiguration = '';
  public nbCylindre = 0;
  public enginePosition = '';
  public prixTotal = 0;
  public prixModif = 0;
  public aspiration = '';
  public speed = 0;
  public handling = 0;
  public accelerate = 0;
  public launch = 0;
  public braking = 0;
  public offroad = 0;
  public pi = 0;
  public class = '';
  public imatriculation = '';
}
