export class OriginalCarDTO {
  public IdCar = '';
  public CarId = 0;
  public CarOrdinal = 0;
  public Maker = '';
  public Model = '';
  public Year = 0;
  public PowerHp = 0;
  public WeightKg = 0;
  public DriveTrain = '';
  public Class = '';
  public Pi = 0;
  public OnRoad = false;
  public Speed = 0;
  public Handling = 0;
  public Accelerate = 0;
  public Launch = 0;
  public Braking = 0;
  public Offroad = 0;
  public RequiredDlc = false;
  public Aviability = '';
  public Price = 0;
  public Type = '';
  public Rarity = '';
  public WikiLink = '';
  public PictureLink = '';
}
