<template>
  <v-container fluid>
    <v-card>
      <!-- CarList of user-->
      <v-tabs v-model="tabs" background-color="transparent" grow>
        <v-tabs-slider></v-tabs-slider>
        <v-tab>
          <v-icon>mdi-car</v-icon>
        </v-tab>

        <v-tab-item>
          <v-container id="user-profile" fluid tag="section">
            <v-row justify="center">
              <v-col>
                <v-card>
                  <v-card-title>
                    Liste des voitures du garage
                    <v-spacer></v-spacer>
                    <v-text-field
                      v-model="search"
                      append-icon="mdi-magnify"
                      label="Recherche"
                      single-line
                      hide-details
                    ></v-text-field>
                  </v-card-title>
                  <v-data-table
                    :headers="headers"
                    :items="voitures"
                    :search="search"
                    :items-per-page="15"
                    show-expand
                    single-expand
                    item-key="model"
                  >
                    <template v-slot:expanded-item>
                      <v-card>aaa</v-card>
                    </template>
                  </v-data-table>
                </v-card>
              </v-col>
            </v-row>
          </v-container>
        </v-tab-item>

        <!--User Profil-->
        <v-tab>
          <v-icon>mdi-account-box</v-icon>
        </v-tab>

        <v-tab-item>
          <v-container id="user-profile" fluid tag="section">
            <v-row justify="center">
              <v-col cols="12" md="4">
                <v-card-text class="text-center">
                  <v-avatar color="red" size="74">
                    <span class="white--text text-h4">CJ</span>
                  </v-avatar>
                  <h4 class="display-2 font-weight-light mb-3 black--text">Alec Thompson</h4>
                </v-card-text>
              </v-col>
            </v-row>
          </v-container>
        </v-tab-item>
      </v-tabs>
    </v-card>
  </v-container>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { AuthModule } from '@/store/modules/Authentication';

@Component
export default class Test extends Vue {
  private isConnected = false;
  async mounted() {
    this.isConnected = await AuthModule.isLoggedIn();
  }
  private search = '';
  private headers = [
    {
      text: 'Model',
      align: 'start',
      value: 'model',
    },
    { text: 'Marque', value: 'maker' },
    { text: 'Class', value: 'pi' },
    { text: 'Prix', value: 'price' },
  ];
  private voitures = [
    {
      idCar: '507a6690-ec51-4a97-bad0-00c3985b20c3',
      carId: 566,
      carOrdinal: 2147,
      maker: 'MG',
      model: 'Metro 6R4',
      year: 1986,
      powerBhp: 410,
      powerKw: 306,
      torqueLbft: 270,
      torqueNm: 366,
      weightLbs: 2271,
      weightKg: 1030,
      engineDisplacement: 3,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V6',
      enginePosition: 'Mid_Engine',
      transmission: 'AWD',
      gearBox: 5,
      speed: 4.6,
      handling: 5.9,
      accelerate: 8.8,
      launch: 8.2,
      braking: 5.8,
      offroad: 7.5,
      pi: 811,
      class: '811',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: -1,
      type: 'Rally_Monsters',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/MG_Metro_6R4',
      pictureLink: null,
    },
    {
      idCar: '8fc7e1f7-8803-41cb-bb72-00dfc44e0161',
      carId: 108,
      carOrdinal: 2416,
      maker: 'Meyers',
      model: 'Manx',
      year: 1971,
      powerBhp: 60,
      powerKw: 45,
      torqueLbft: 82,
      torqueNm: 111,
      weightLbs: 1235,
      weightKg: 560,
      engineDisplacement: 1.5,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'F4',
      enginePosition: 'Rear_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 3.1,
      handling: 4.3,
      accelerate: 2.9,
      launch: 5.3,
      braking: 2.6,
      offroad: 5.9,
      pi: 291,
      class: '291',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: -1,
      type: 'Cult_Cars',
      rarity: 'Epic',
      wikiLink: 'https://forza.fandom.com/wiki/Meyers_Manx',
      pictureLink: null,
    },
    {
      idCar: 'f7c9e2ad-1e9a-4985-be05-0168fbc259b9',
      carId: 597,
      carOrdinal: 1045,
      maker: 'Pontiac',
      model: 'Firebird Trans Am GTA',
      year: 1987,
      powerBhp: 216,
      powerKw: 161,
      torqueLbft: 315,
      torqueNm: 427,
      weightLbs: 3483,
      weightKg: 1580,
      engineDisplacement: 5.7,
      nbCylindre: 8,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 5.5,
      handling: 4.1,
      accelerate: 3.4,
      launch: 3.1,
      braking: 2.4,
      offroad: 4.8,
      pi: 485,
      class: '485',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 25000,
      type: 'Retro_Muscle',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Pontiac_Firebird_Trans_Am_GTA',
      pictureLink: null,
    },
    {
      idCar: '9ba013ce-3a24-4773-8128-018c261e043c',
      carId: 522,
      carOrdinal: 2992,
      maker: 'Jaguar',
      model: 'Lightweight E-Type',
      year: 1964,
      powerBhp: 340,
      powerKw: 254,
      torqueLbft: 314,
      torqueNm: 426,
      weightLbs: 2292,
      weightKg: 1040,
      engineDisplacement: 3.8,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I6',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 6.3,
      handling: 4.4,
      accelerate: 4.7,
      launch: 4.4,
      braking: 3.4,
      offroad: 4.6,
      pi: 688,
      class: '688',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 7500000,
      type: 'Classic_Racers',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Jaguar_Lightweight_E-Type',
      pictureLink: null,
    },
    {
      idCar: '71f81953-3e65-4c00-a9f0-018ec4b9473f',
      carId: 630,
      carOrdinal: 1369,
      maker: 'Pagani',
      model: 'Zonda Cinque Roadster',
      year: 2009,
      powerBhp: 678,
      powerKw: 506,
      torqueLbft: 575,
      torqueNm: 780,
      weightLbs: 2858,
      weightKg: 1296,
      engineDisplacement: 7.3,
      nbCylindre: 12,
      aspiration: 'Naturally_Aspirated ',
      engineConfiguration: 'V12',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 7.4,
      handling: 8,
      accelerate: 6.5,
      launch: 6.9,
      braking: 8.9,
      offroad: 4.5,
      pi: 896,
      class: '896',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 2100000,
      type: 'Hypercars',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Pagani_Zonda_Cinque_Roadster',
      pictureLink: null,
    },
    {
      idCar: '85fe05ef-2059-4be6-b007-020c649f35dc',
      carId: 455,
      carOrdinal: 2636,
      maker: 'Toyota',
      model: '#1 T100 Baja Truck',
      year: 1993,
      powerBhp: 360,
      powerKw: 268,
      torqueLbft: 265,
      torqueNm: 359,
      weightLbs: 4000,
      weightKg: 1814,
      engineDisplacement: 3.4,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V6',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 4.7,
      handling: 3.7,
      accelerate: 5.9,
      launch: 6,
      braking: 4.7,
      offroad: 10,
      pi: 693,
      class: '693',
      requiredDlc: 'No Dlc Required',
      aviability: 'Wheelspin',
      price: 500000,
      type: 'UUnlimited_Offroad',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Toyota_1_T100_Baja_Truck',
      pictureLink: null,
    },
    {
      idCar: '1e7bd013-fe24-4705-9ae0-02b1534ae1e5',
      carId: 483,
      carOrdinal: 344,
      maker: 'Nissan',
      model: 'Fairlady Z',
      year: 2003,
      powerBhp: 287,
      powerKw: 214,
      torqueLbft: 273,
      torqueNm: 370,
      weightLbs: 3310,
      weightKg: 1501,
      engineDisplacement: 3.5,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V6',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 6.5,
      handling: 5.5,
      accelerate: 4.6,
      launch: 4,
      braking: 3.5,
      offroad: 4.8,
      pi: 650,
      class: '650',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 35000,
      type: 'Modern_Sports_Cars',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Nissan_Fairlady_Z',
      pictureLink: null,
    },
    {
      idCar: 'fec48824-f94a-4659-a925-03669ab7a3bf',
      carId: 474,
      carOrdinal: 1296,
      maker: 'Mercedes-Benz',
      model: '190E 2.5-16 Evolution II',
      year: 1990,
      powerBhp: 235,
      powerKw: 175,
      torqueLbft: 181,
      torqueNm: 245,
      weightLbs: 2954,
      weightKg: 1340,
      engineDisplacement: 2.5,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 6.2,
      handling: 4.9,
      accelerate: 4,
      launch: 3.6,
      braking: 2.9,
      offroad: 4.4,
      pi: 579,
      class: '579',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 150000,
      type: 'Retro_Saloons',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Mercedes-Benz_190E_2.5-16_Evolution_II',
      pictureLink: null,
    },
    {
      idCar: '61976023-7b90-47a5-9610-03774a69ca86',
      carId: 684,
      carOrdinal: 2467,
      maker: 'Ferrari',
      model: '488 GTB',
      year: 2015,
      powerBhp: 660,
      powerKw: 492,
      torqueLbft: 560,
      torqueNm: 760,
      weightLbs: 3252,
      weightKg: 1475,
      engineDisplacement: 3.9,
      nbCylindre: 8,
      aspiration: 'Twin_Turbocharged',
      engineConfiguration: 'V8',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 7,
      speed: 8.2,
      handling: 7.9,
      accelerate: 6.8,
      launch: 6.5,
      braking: 7.8,
      offroad: 4.4,
      pi: 863,
      class: '863',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 290000,
      type: 'Modern_Supercars',
      rarity: 'Epic',
      wikiLink: 'https://forza.fandom.com/wiki/Ferrari_488_GTB',
      pictureLink: null,
    },
    {
      idCar: '0abad4ad-6098-4343-9f54-037765ed6866',
      carId: 642,
      carOrdinal: 1042,
      maker: 'Nissan',
      model: 'Skyline 2000GT-R',
      year: 1971,
      powerBhp: 160,
      powerKw: 119,
      torqueLbft: 133,
      torqueNm: 180,
      weightLbs: 2425,
      weightKg: 1100,
      engineDisplacement: 2,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I6',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 4.7,
      handling: 4.4,
      accelerate: 3.6,
      launch: 2.5,
      braking: 2.6,
      offroad: 5,
      pi: 493,
      class: '493',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 60000,
      type: 'Classic_Sports_Cars',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Nissan_Skyline_2000GT-R',
      pictureLink: null,
    },
    {
      idCar: '7d1ad89c-e2ee-4b8d-a1cf-0432ea45be7f',
      carId: 668,
      carOrdinal: 424,
      maker: 'Mazda',
      model: 'RX-7',
      year: 1997,
      powerBhp: 261,
      powerKw: 195,
      torqueLbft: 217,
      torqueNm: 294,
      weightLbs: 2831,
      weightKg: 1284,
      engineDisplacement: 1.3,
      nbCylindre: 0,
      aspiration: 'Twin_Turbocharged',
      engineConfiguration: '2-Rotor-Rotary',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 6.6,
      handling: 5.5,
      accelerate: 4.8,
      launch: 3,
      braking: 3.3,
      offroad: 5,
      pi: 645,
      class: '645',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 35000,
      type: 'Retro_Sports_Cars',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Mazda_RX-7',
      pictureLink: null,
    },
    {
      idCar: '8d50d8e8-eb50-4160-b871-0516b51f4332',
      carId: 484,
      carOrdinal: 2732,
      maker: 'Hoonigan',
      model: 'Mazda RX-7 Twerkstallion',
      year: 1992,
      powerBhp: 600,
      powerKw: 447,
      torqueLbft: 590,
      torqueNm: 800,
      weightLbs: 2866,
      weightKg: 1300,
      engineDisplacement: 5.3,
      nbCylindre: 8,
      aspiration: 'Turbocharged',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 8.3,
      handling: 5.8,
      accelerate: 4.6,
      launch: 4.7,
      braking: 4.5,
      offroad: 3.8,
      pi: 799,
      class: '799',
      requiredDlc: 'No Dlc Required',
      aviability: 'Wheelspin',
      price: 50000,
      type: 'Drift_Cars',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Hoonigan_Mazda_RX-7_Twerkstallion',
      pictureLink: null,
    },
    {
      idCar: 'bb23d52f-b6bf-4be2-83a8-054f7927f38b',
      carId: 693,
      carOrdinal: 489,
      maker: 'Jaguar',
      model: 'XJ220',
      year: 1993,
      powerBhp: 542,
      powerKw: 404,
      torqueLbft: 473,
      torqueNm: 641,
      weightLbs: 3241,
      weightKg: 1470,
      engineDisplacement: 3.5,
      nbCylindre: 6,
      aspiration: 'Twin_Turbocharged',
      engineConfiguration: 'V6',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 7.7,
      handling: 6.4,
      accelerate: 5.2,
      launch: 2.2,
      braking: 5.2,
      offroad: 4.8,
      pi: 786,
      class: '786',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: -1,
      type: 'Retro_Sports_Cars',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Jaguar_XJ220',
      pictureLink: null,
    },
    {
      idCar: 'ea8743cb-fdba-40c1-b577-05e1f2328fe4',
      carId: 128,
      carOrdinal: 306,
      maker: 'Shelby',
      model: 'Cobra 427 S/C',
      year: 1965,
      powerBhp: 425,
      powerKw: 317,
      torqueLbft: 500,
      torqueNm: 678,
      weightLbs: 2350,
      weightKg: 1066,
      engineDisplacement: 7,
      nbCylindre: 8,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 5.9,
      handling: 4.1,
      accelerate: 4.5,
      launch: 4.6,
      braking: 3.2,
      offroad: 4.5,
      pi: 694,
      class: '694',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 2100000,
      type: 'Rare_Classics',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Shelby_Cobra_427_S/C',
      pictureLink: null,
    },
    {
      idCar: '3e86670a-7ebf-4679-b497-08233d3f94d0',
      carId: 10,
      carOrdinal: 1046,
      maker: 'Dodge',
      model: 'Viper SRT10 ACR',
      year: 2008,
      powerBhp: 600,
      powerKw: 447,
      torqueLbft: 560,
      torqueNm: 760,
      weightLbs: 3408,
      weightKg: 1546,
      engineDisplacement: 8.4,
      nbCylindre: 10,
      aspiration: 'Naturally_Aspirated ',
      engineConfiguration: 'V10',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 7.2,
      handling: 7.9,
      accelerate: 5.6,
      launch: 4.7,
      braking: 7.5,
      offroad: 4.8,
      pi: 844,
      class: '844',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 90000,
      type: 'Track_Toys',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Dodge_Viper_SRT10_ACR',
      pictureLink: null,
    },
    {
      idCar: 'cf3a67f6-bfba-40dc-b9a9-088f7a2f8e84',
      carId: 418,
      carOrdinal: 2507,
      maker: 'Chevrolet',
      model: '150 Utility Sedan',
      year: 1955,
      powerBhp: 180,
      powerKw: 134,
      torqueLbft: 260,
      torqueNm: 353,
      weightLbs: 3389,
      weightKg: 1537,
      engineDisplacement: 4.3,
      nbCylindre: 8,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 3,
      speed: 4.5,
      handling: 3.5,
      accelerate: 3.2,
      launch: 2.5,
      braking: 2,
      offroad: 5.8,
      pi: 360,
      class: '360',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 35000,
      type: 'Rods_And_Customs',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Chevrolet_150_Utility_Sedan',
      pictureLink: null,
    },
    {
      idCar: '73141149-a086-4424-9a11-08eec4befd13',
      carId: 402,
      carOrdinal: 2371,
      maker: 'Ferrari',
      model: 'FXX K',
      year: 2014,
      powerBhp: 1036,
      powerKw: 773,
      torqueLbft: 664,
      torqueNm: 900,
      weightLbs: 2831,
      weightKg: 1284,
      engineDisplacement: 6.3,
      nbCylindre: 0,
      aspiration: 'Naturally_Aspirated Hybrid V12HY-KERS u',
      engineConfiguration: 'V12',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 7,
      speed: 8.1,
      handling: 10,
      accelerate: 8.1,
      launch: 9,
      braking: 10,
      offroad: 3.6,
      pi: 979,
      class: '979',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 2700000,
      type: 'Extreme_Track_Toys',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Ferrari_FXX_K',
      pictureLink: null,
    },
    {
      idCar: 'c5d2bf6b-998d-4fcf-84b7-09396738d650',
      carId: 190,
      carOrdinal: 3250,
      maker: 'Mercedes-Benz',
      model: 'Mercedes-Benz E 63 S',
      year: 2018,
      powerBhp: 603,
      powerKw: 450,
      torqueLbft: 626,
      torqueNm: 849,
      weightLbs: 4515,
      weightKg: 2048,
      engineDisplacement: 4,
      nbCylindre: 8,
      aspiration: 'Twin_Turbocharged',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'AWD',
      gearBox: 9,
      speed: 7.6,
      handling: 6,
      accelerate: 8.7,
      launch: 9.7,
      braking: 4.8,
      offroad: 5.1,
      pi: 778,
      class: '778',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: -1,
      type: 'Super_Saloons',
      rarity: 'Epic',
      wikiLink: 'https://forza.fandom.com/wiki/Mercedes-Benz_E_63_S',
      pictureLink: null,
    },
    {
      idCar: '29a38092-b1d8-44c0-bc49-096adc454789',
      carId: 2,
      carOrdinal: 2568,
      maker: 'Volkswagen',
      model: 'Class 5/1600 Baja Bug',
      year: 1969,
      powerBhp: 80,
      powerKw: 60,
      torqueLbft: 106,
      torqueNm: 144,
      weightLbs: 2400,
      weightKg: 1089,
      engineDisplacement: 1.6,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Rear_Engine',
      transmission: 'FWD',
      gearBox: 4,
      speed: 3.5,
      handling: 4.6,
      accelerate: 2.5,
      launch: 4.7,
      braking: 3.1,
      offroad: 7.7,
      pi: 349,
      class: '349',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 60000,
      type: 'Buggies',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Volkswagen_Class_5/1600_Baja_Bug',
      pictureLink: null,
    },
    {
      idCar: 'f5a3580b-5dfa-4f4c-9630-09b58d31b9ce',
      carId: 592,
      carOrdinal: 2372,
      maker: 'Ford',
      model: 'De Luxe Five-Window Coupe',
      year: 1932,
      powerBhp: 65,
      powerKw: 48,
      torqueLbft: 130,
      torqueNm: 176,
      weightLbs: 2398,
      weightKg: 1088,
      engineDisplacement: 3.6,
      nbCylindre: 8,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 3,
      speed: 3.2,
      handling: 3.9,
      accelerate: 1.9,
      launch: 2.8,
      braking: 1.8,
      offroad: 4.8,
      pi: 126,
      class: '126',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 35000,
      type: 'Rods_And_Customs',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Ford_De_Luxe_Five-Window_Coupe',
      pictureLink: null,
    },
    {
      idCar: '25488d8c-49b1-417b-8056-09c1d25d926f',
      carId: 193,
      carOrdinal: 3227,
      maker: 'Ford',
      model: 'Racing Puma',
      year: 1999,
      powerBhp: 153,
      powerKw: 114,
      torqueLbft: 119,
      torqueNm: 161,
      weightLbs: 2588,
      weightKg: 1174,
      engineDisplacement: 1.7,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Front_Engine',
      transmission: 'FWD',
      gearBox: 5,
      speed: 4.9,
      handling: 4.6,
      accelerate: 3.5,
      launch: 2.7,
      braking: 3.3,
      offroad: 5,
      pi: 514,
      class: '514',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 20000,
      type: 'Retro_Rally',
      rarity: 'Rare',
      wikiLink: 'https://forza.fandom.com/wiki/Ford_Racing_Puma',
      pictureLink: null,
    },
    {
      idCar: '46822662-0dc0-4bde-9515-09e201795a19',
      carId: 136,
      carOrdinal: 2005,
      maker: 'Honda',
      model: 'S2000 CR',
      year: 2009,
      powerBhp: 237,
      powerKw: 177,
      torqueLbft: 162,
      torqueNm: 220,
      weightLbs: 2813,
      weightKg: 1276,
      engineDisplacement: 2,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 5.7,
      handling: 5.7,
      accelerate: 4.6,
      launch: 3.7,
      braking: 3.7,
      offroad: 5,
      pi: 634,
      class: '634',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 25000,
      type: 'Modern_Sports_Cars',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Honda_S2000_CR',
      pictureLink: null,
    },
    {
      idCar: '8eea2a5b-ab44-4e55-ba27-0b1e97a43752',
      carId: 541,
      carOrdinal: 2911,
      maker: 'Morris',
      model: 'Minor 1000',
      year: 1958,
      powerBhp: 37,
      powerKw: 28,
      torqueLbft: 48,
      torqueNm: 65,
      weightLbs: 1764,
      weightKg: 800,
      engineDisplacement: 1,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 2.7,
      handling: 4,
      accelerate: 1.6,
      launch: 2.1,
      braking: 1.9,
      offroad: 5.6,
      pi: 100,
      class: '100',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 20000,
      type: 'Cult_Cars',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/Morris_Minor_1000',
      pictureLink: null,
    },
    {
      idCar: '4d564e86-1e12-410f-9001-0b4e45634edc',
      carId: 479,
      carOrdinal: 2422,
      maker: 'HSV',
      model: 'Limited Edition Gen-F GTS Maloo',
      year: 2014,
      powerBhp: 577,
      powerKw: 430,
      torqueLbft: 546,
      torqueNm: 740,
      weightLbs: 4034,
      weightKg: 1830,
      engineDisplacement: 6.2,
      nbCylindre: 8,
      aspiration: 'Supercharged',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 6.5,
      handling: 5.5,
      accelerate: 4.8,
      launch: 4.6,
      braking: 4.8,
      offroad: 4.4,
      pi: 742,
      class: '742',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 62000,
      type: 'Vans_Utility',
      rarity: 'Common',
      wikiLink: 'https://forza.fandom.com/wiki/HSV_Limited_Edition_Gen-F_GTS_Maloo',
      pictureLink: null,
    },
    {
      idCar: '4f52add2-9c4d-4d1c-a01b-0d00ce755a63',
      carId: 111,
      carOrdinal: 336,
      maker: 'Jaguar',
      model: 'E-type S1',
      year: 1961,
      powerBhp: 265,
      powerKw: 198,
      torqueLbft: 260,
      torqueNm: 353,
      weightLbs: 2900,
      weightKg: 1315,
      engineDisplacement: 3.8,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I6',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 5.2,
      handling: 4.2,
      accelerate: 4,
      launch: 2.8,
      braking: 2.7,
      offroad: 5.2,
      pi: 525,
      class: '525',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 150000,
      type: 'Rare_Classics',
      rarity: 'Epic',
      wikiLink: 'https://forza.fandom.com/wiki/Jaguar_E-type_S1',
      pictureLink: null,
    },
    {
      idCar: '0a36de7e-e308-4b3f-9fa6-0dc0d6092b5e',
      carId: 399,
      carOrdinal: 483,
      maker: 'Dodge',
      model: 'Viper GTS ACR',
      year: 1999,
      powerBhp: 460,
      powerKw: 343,
      torqueLbft: 500,
      torqueNm: 678,
      weightLbs: 3450,
      weightKg: 1565,
      engineDisplacement: 8,
      nbCylindre: 10,
      aspiration: 'Naturally_Aspirated ',
      engineConfiguration: 'V10',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 6,
      speed: 6.9,
      handling: 5.5,
      accelerate: 5.2,
      launch: 4.1,
      braking: 4,
      offroad: 4.5,
      pi: 717,
      class: '717',
      requiredDlc: 'No Dlc Required',
      aviability: 'Wheelspin',
      price: 75000,
      type: 'Retro_Muscle',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Dodge_Viper_GTS_ACR',
      pictureLink: null,
    },
    {
      idCar: '4996014c-dab8-4872-9913-0e4cd7e6c5fc',
      carId: 221,
      carOrdinal: 455,
      maker: 'Toyota',
      model: 'Sprinter Trueno GT Apex',
      year: 1985,
      powerBhp: 128,
      powerKw: 95,
      torqueLbft: 110,
      torqueNm: 149,
      weightLbs: 2094,
      weightKg: 950,
      engineDisplacement: 1.6,
      nbCylindre: 4,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I4',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 4.5,
      handling: 4.3,
      accelerate: 4,
      launch: 3.4,
      braking: 2.6,
      offroad: 5.2,
      pi: 480,
      class: '480',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: -1,
      type: 'Retro_Sports_Cars',
      rarity: 'Epic',
      wikiLink: 'https://forza.fandom.com/wiki/Toyota_Sprinter_Trueno_GT_Apex',
      pictureLink: null,
    },
    {
      idCar: 'a9600ee8-8f5a-4bee-82e9-0e7e63b07c43',
      carId: 114,
      carOrdinal: 1372,
      maker: 'Bentley',
      model: '8-Liter',
      year: 1931,
      powerBhp: 220,
      powerKw: 164,
      torqueLbft: 383,
      torqueNm: 519,
      weightLbs: 5600,
      weightKg: 2540,
      engineDisplacement: 8,
      nbCylindre: 6,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'I6',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 3.7,
      handling: 3.5,
      accelerate: 2.4,
      launch: 1.8,
      braking: 1.8,
      offroad: 5.7,
      pi: 181,
      class: '181',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 1500000,
      type: 'Rare_Classics',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Bentley_8-Liter',
      pictureLink: null,
    },
    {
      idCar: '869a0eb3-4806-424b-9b7b-0f65e37fe291',
      carId: 622,
      carOrdinal: 567,
      maker: 'Nissan',
      model: 'R390',
      year: 1998,
      powerBhp: 550,
      powerKw: 410,
      torqueLbft: 471,
      torqueNm: 639,
      weightLbs: 2264,
      weightKg: 1027,
      engineDisplacement: 3.5,
      nbCylindre: 8,
      aspiration: 'Twin_Turbocharged',
      engineConfiguration: 'V8',
      enginePosition: 'Mid_Engine',
      transmission: 'RWD',
      gearBox: 5,
      speed: 7.1,
      handling: 7.8,
      accelerate: 6.3,
      launch: 2.5,
      braking: 7.1,
      offroad: 3.5,
      pi: 859,
      class: '859',
      requiredDlc: 'No Dlc Required',
      aviability: 'Autoshow',
      price: 1250000,
      type: 'Retro_Super_Cars',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Nissan_R390',
      pictureLink: null,
    },
    {
      idCar: '954cfb5a-26bb-433a-991c-0fa75163916f',
      carId: 417,
      carOrdinal: 1581,
      maker: 'Ford',
      model: 'F-100',
      year: 1956,
      powerBhp: 173,
      powerKw: 129,
      torqueLbft: 260,
      torqueNm: 353,
      weightLbs: 3325,
      weightKg: 1508,
      engineDisplacement: 4.5,
      nbCylindre: 8,
      aspiration: 'Naturally_Aspirated',
      engineConfiguration: 'V8',
      enginePosition: 'Front_Engine',
      transmission: 'RWD',
      gearBox: 4,
      speed: 3.8,
      handling: 2.7,
      accelerate: 3.1,
      launch: 3,
      braking: 2.1,
      offroad: 6.9,
      pi: 302,
      class: '302',
      requiredDlc: 'No Dlc Required',
      aviability: 'Wheelspin',
      price: 36000,
      type: 'Rods_And_Customs',
      rarity: 'Legendary',
      wikiLink: 'https://forza.fandom.com/wiki/Ford_F-100',
      pictureLink: null,
    },
  ];
  private voiture = { class: 'A' };
}
</script>
<style></style>
