FROM node:lts-alpine as build-stage

RUN mkdir -p /home/node/GuanajuatoWeb
WORKDIR /home/node/GuanajuatoWeb

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# étape de production
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage home/node/GuanajuatoWeb/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]